baseURL = "https://p.umputun.com/"
languageCode = "ru-ru"
title = "Umputun тут был"
theme = "hyde-hyde"

summarylength = 40
enableEmoji = true
paginate = 25

GoogleAnalytics = "UA-20349923-1"
enableSourceMap = false

[params.social]
gravatar = "umputun@gmail.com"
github = "umputun"
twitter = "umputun"
telegram = "umputun"
email= "umputun@gmail.com"

[params.meta]
keywords = "Umputun, Умпутун, blog umputun, блог умпутуна"
description = "заметки на разные темы"
longDescription = "Заметки на разные темы от Umputun. Старший брат моего твиттера."

[params]
author = "Umputun"
description = "заметки на разные темы"
longDescription = "Заметки на разные темы от Umputun. Старший брат моего твиттера."
authorimage = "/images/p-240.png"
copyright = "umputun"
license = "CC BY-SA 4.0"
licenseURL = "https://creativecommons.org/licenses/by-sa/4.0/deed.ru"
postNavigation = false

themeColor="theme-base-00"
Remark42=true
dateformat="2006-02-01"

[permalinks]
posts = "/:year/:month/:day/:filename"

[menu]

  [[menu.main]]
  name = " Домой"
  identifier = "home"
  url = "/"

  [[menu.main]]
  name = "Еженедельный подкаст от Umputun"
  identifier = "podcast_umputun"
  url = "https://podcast.umputun.com/"

  [[menu.main]]
  name = "Подкаст Радио-Т"
  identifier = "podcast_radiot"
  url = "https://radio-t.com/"

  [[menu.main]]
  name = "Помочь на patreon"
  identifier = "patreon"
  url = "https://www.patreon.com/user?u=2577215"

[taxonomies]
  tag = "tags"

[markup]

  [markup.highlight]
  codeFences = true
  guessSyntax = false
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true # if false, you need to provide you own custom CSS
  style = "monokai"
  tabWidth = 4  

[author]
  name = "umputun"
